(function() {
	//地图服务端口号
	var MAPSERVICE_PORT="8090";
	//房屋基础服务平台端口号
	var HOUSEBASICAPP_PORT="8080";	
	//房屋安全应用端口号
	var HOUSESAFEAPP_PORT="8081";
    
	FMapLib.MAPSERVICE_PORT=MAPSERVICE_PORT;
	FMapLib.HOUSEBASICAPP_PORT=HOUSEBASICAPP_PORT;	
	FMapLib.HOUSESAFEAPP_PORT=HOUSESAFEAPP_PORT;	
})();	