package com.originsys.access.action;

import java.io.PrintWriter;
import java.sql.Array;
import java.util.ArrayList;
import java.util.List;

import javax.servlet.http.HttpServletResponse;

import net.sf.json.JSONArray;

import com.ibatis.sqlmap.client.SqlMapClient;
import com.originsys.eap.action.BaseAction;
import com.originsys.eap.iservice.IData;
import com.originsys.eap.util.DataSource;
import com.originsys.eap.util.RequestAction;
import com.originsys.access.domain.HouseHeightRange;

public class regionthemepie extends BaseAction implements IData{
	public void execute(RequestAction arg0, HttpServletResponse response) throws Exception {
	String arrayString="";
    response.setContentType("application/javascript");  
    response.setHeader("P3P","CP=\"CURa ADMa DEVa PSAo PSDo OUR BUS UNI PUR INT DEM STA PRE COM NAV OTC NOI DSP COR\"");  
    response.setCharacterEncoding("utf-8");  
    PrintWriter out = response.getWriter();  
	String jsoncallback = arg0.getParameter("jsoncallback");
	SqlMapClient sc=DataSource.getSqlMapInstance();//定义一个操作数据库的ibatis接口变量
	List<HouseHeightRange>lxhousenum=(List)sc.queryForList("Access.regionthemebystructurelx");//从数据库中选择以当前页的起始条数为起点，当前页面显示条数为长度的记录数
	List<HouseHeightRange>szhousenum=(List)sc.queryForList("Access.regionthemebystructuresz");
	List<HouseHeightRange>hyhousenum=(List)sc.queryForList("Access.regionthemebystructurehy");
	List<HouseHeightRange>tqhousenum=(List)sc.queryForList("Access.regionthemebystructuretq");
	List<HouseHeightRange>lchousenum=(List)sc.queryForList("Access.regionthemebystructurelc");
	List<HouseHeightRange>gxhousenum=(List)sc.queryForList("Access.regionthemebystructuregx");
	List<HouseHeightRange>cqhousenum=(List)sc.queryForList("Access.regionthemebystructurecq");
	HouseHeightRange house0=(HouseHeightRange) lxhousenum.get(0);
	HouseHeightRange house1=(HouseHeightRange) lxhousenum.get(1);
	HouseHeightRange house2=(HouseHeightRange) lxhousenum.get(2);
	HouseHeightRange house3=(HouseHeightRange) lxhousenum.get(3);
	HouseHeightRange house4=(HouseHeightRange) lxhousenum.get(4);
	HouseHeightRange house5=(HouseHeightRange) lxhousenum.get(5);
	HouseHeightRange house6=(HouseHeightRange) lxhousenum.get(6);
	house0.range_name ="钢结构";
	house1.range_name ="钢、钢混结构";
	house2.range_name ="钢砼结构";
	house3.range_name ="混合结构";
	house4.range_name ="砖木结构";
	house5.range_name ="木结构";
	house6.range_name ="其他结构";
	HouseHeightRange house7=(HouseHeightRange) szhousenum.get(0);
	HouseHeightRange house8=(HouseHeightRange) szhousenum.get(1);
	HouseHeightRange house9=(HouseHeightRange) szhousenum.get(2);
	HouseHeightRange house10=(HouseHeightRange) szhousenum.get(3);
	HouseHeightRange house11=(HouseHeightRange) szhousenum.get(4);
	HouseHeightRange house12=(HouseHeightRange) szhousenum.get(5);
	HouseHeightRange house13=(HouseHeightRange) szhousenum.get(6);
	house7.range_name ="钢结构";
	house8.range_name ="钢、钢混结构";
	house9.range_name ="钢砼结构";
	house10.range_name ="混合结构";
	house11.range_name ="砖木结构";
	house12.range_name ="木结构";
	house13.range_name ="其他结构";
	HouseHeightRange house14=(HouseHeightRange) hyhousenum.get(0);
	HouseHeightRange house15=(HouseHeightRange) hyhousenum.get(1);
	HouseHeightRange house16=(HouseHeightRange) hyhousenum.get(2);
	HouseHeightRange house17=(HouseHeightRange) hyhousenum.get(3);
	HouseHeightRange house18=(HouseHeightRange) hyhousenum.get(4);
	HouseHeightRange house19=(HouseHeightRange) hyhousenum.get(5);
	HouseHeightRange house20=(HouseHeightRange) hyhousenum.get(6);
	house14.range_name ="钢结构";
	house15.range_name ="钢、钢混结构";
	house16.range_name ="钢砼结构";
	house17.range_name ="混合结构";
	house18.range_name ="砖木结构";
	house19.range_name ="木结构";
	house20.range_name ="其他结构";
	HouseHeightRange house21=(HouseHeightRange) tqhousenum.get(0);
	HouseHeightRange house22=(HouseHeightRange) tqhousenum.get(1);
	HouseHeightRange house23=(HouseHeightRange) tqhousenum.get(2);
	HouseHeightRange house24=(HouseHeightRange) tqhousenum.get(3);
	HouseHeightRange house25=(HouseHeightRange) tqhousenum.get(4);
	HouseHeightRange house26=(HouseHeightRange) tqhousenum.get(5);
	HouseHeightRange house27=(HouseHeightRange) tqhousenum.get(6);
	house21.range_name ="钢结构";
	house22.range_name ="钢、钢混结构";
	house23.range_name ="钢砼结构";
	house24.range_name ="混合结构";
	house25.range_name ="砖木结构";
	house26.range_name ="木结构";
	house27.range_name ="其他结构";
	HouseHeightRange house28=(HouseHeightRange) lchousenum.get(0);
	HouseHeightRange house29=(HouseHeightRange) lchousenum.get(1);
	HouseHeightRange house30=(HouseHeightRange) lchousenum.get(2);
	HouseHeightRange house31=(HouseHeightRange) lchousenum.get(3);
	HouseHeightRange house32=(HouseHeightRange) lchousenum.get(4);
	HouseHeightRange house33=(HouseHeightRange) lchousenum.get(5);
	HouseHeightRange house34=(HouseHeightRange) lchousenum.get(6);
	house28.range_name ="钢结构";
	house29.range_name ="钢、钢混结构";
	house30.range_name ="钢砼结构";
	house31.range_name ="混合结构";
	house32.range_name ="砖木结构";
	house33.range_name ="木结构";
	house34.range_name ="其他结构";
	HouseHeightRange house35=(HouseHeightRange) gxhousenum.get(0);
	HouseHeightRange house36=(HouseHeightRange) gxhousenum.get(1);
	HouseHeightRange house37=(HouseHeightRange) gxhousenum.get(2);
	HouseHeightRange house38=(HouseHeightRange) gxhousenum.get(3);
	HouseHeightRange house39=(HouseHeightRange) gxhousenum.get(4);
	HouseHeightRange house40=(HouseHeightRange) gxhousenum.get(5);
	HouseHeightRange house41=(HouseHeightRange) gxhousenum.get(6);
	house35.range_name ="钢结构";
	house36.range_name ="钢、钢混结构";
	house37.range_name ="钢砼结构";
	house38.range_name ="混合结构";
	house39.range_name ="砖木结构";
	house40.range_name ="木结构";
	house41.range_name ="其他结构";
	HouseHeightRange house42=(HouseHeightRange) cqhousenum.get(0);
	HouseHeightRange house43=(HouseHeightRange) cqhousenum.get(1);
	HouseHeightRange house44=(HouseHeightRange) cqhousenum.get(2);
	HouseHeightRange house45=(HouseHeightRange) cqhousenum.get(3);
	HouseHeightRange house46=(HouseHeightRange) cqhousenum.get(4);
	HouseHeightRange house47=(HouseHeightRange) cqhousenum.get(5);
	HouseHeightRange house48=(HouseHeightRange) cqhousenum.get(6);
	house42.range_name ="钢结构";
	house43.range_name ="钢、钢混结构";
	house44.range_name ="钢砼结构";
	house45.range_name ="混合结构";
	house46.range_name ="砖木结构";
	house47.range_name ="木结构";
	house48.range_name ="其他结构";
	ArrayList housenum=new ArrayList<List>();
	housenum.add(lxhousenum);
	housenum.add(szhousenum);
	housenum.add(hyhousenum);
	housenum.add(tqhousenum);
	housenum.add(lchousenum);
	housenum.add(gxhousenum);
	housenum.add(cqhousenum);
	String callback=jsoncallback+"("+JSONArray.fromObject(housenum)+");"; 
    out.print(callback); 
}

}
